export const ServerSettings = [
  "ServerName",
  "ServerDescription",
  "AdminPassword",
  "ServerPassword",
  "PublicIP",
  "PublicPort",
  "ServerPlayerMaxNum",
  "bIsUseBackupSaveData",
  "AutoSaveSpan",
  "CrossplayPlatforms",
  "LogFormatType",
  "RandomizerType",
  "RandomizerSeed",
  "bIsRandomizerPalLevelRandom",
  "bEnableVoiceChat",
  "VoiceChatMaxVolumeDistance",
  "VoiceChatZeroVolumeDistance",
];

export const InGameSettings = [
  "DayTimeSpeedRate",
  "NightTimeSpeedRate",
  "ExpRate",
  "PalCaptureRate",
  "PalSpawnNumRate",
  "PalDamageRateAttack",
  "PalDamageRateDefense",
  "PalStomachDecreaceRate",
  "PalStaminaDecreaceRate",
  "PalAutoHPRegeneRate",
  "PalAutoHpRegeneRateInSleep",
  "PlayerDamageRateAttack",
  "PlayerDamageRateDefense",
  "PlayerStomachDecreaceRate",
  "PlayerStaminaDecreaceRate",
  "PlayerAutoHPRegeneRate",
  "PlayerAutoHpRegeneRateInSleep",
  "BuildObjectHpRate",
  "BuildObjectDamageRate",
  "BuildObjectDeteriorationDamageRate",
  "DropItemMaxNum",
  "ItemWeightRate",
  "CollectionDropRate",
  "CollectionObjectHpRate",
  "CollectionObjectRespawnSpeedRate",
  "EnemyDropItemRate",
  "PalEggDefaultHatchingTime",
  "bEnableInvaderEnemy",
  "EnablePredatorBossPal",
  "DeathPenalty",
  "GuildPlayerMaxNum",
  "BaseCampMaxNumInGuild",
  "BaseCampWorkerMaxNum",
  "MaxBuildingLimitNum",
  "SupplyDropSpan",
  "ChatPostLimitPerMinute",
  "EquipmentDurabilityDamageRate",
  "ItemContainerForceMarkDirtyInterval",
  "ItemCorruptionMultiplier",
  "PhysicsActiveDropItemMaxNum",
  "MonsterFarmActionSpeedRate",
];

export const AdvancedSettings = [
  "bEnablePlayerToPlayerDamage",
  "bEnableFriendlyFire",
  "bActiveUNKO",
  "bEnableAimAssistPad",
  "bEnableAimAssistKeyboard",
  "DropItemMaxNum_UNKO",
  "BaseCampMaxNum",
  "DropItemAliveMaxHours",
  "bAutoResetGuildNoOnlinePlayers",
  "AutoResetGuildTimeNoOnlinePlayers",
  "WorkSpeedRate",
  "bIsMultiplay",
  "bIsPvP",
  "bHardcore",
  "bPalLost",
  "bCharacterRecreateInHardcore",
  "bCanPickupOtherGuildDeathPenaltyDrop",
  "bEnableNonLoginPenalty",
  "bEnableFastTravel",
  "bEnableFastTravelOnlyBaseCamp",
  "bIsStartLocationSelectByMap",
  "bExistPlayerAfterLogout",
  "bEnableDefenseOtherGuildPlayer",
  "bInvisibleOtherGuildBaseCampAreaFX",
  "bBuildAreaLimit",
  "ServerReplicatePawnCullDistance",
  "bShowPlayerList",
  "bAllowGlobalPalboxExport",
  "bAllowGlobalPalboxImport",
  "RCONEnabled",
  "RCONPort",
  "RESTAPIEnabled",
  "RESTAPIPort",
  "Region",
  "bUseAuth",
  "BanListURL",
  "bAllowClientMod",
  "bIsShowJoinLeftMessage",
  "DenyTechnologyList",
  "GuildRejoinCooldownMinutes",
  "BlockRespawnTime",
  "RespawnPenaltyDurationThreshold",
  "RespawnPenaltyTimeScale",
  "bDisplayPvPItemNumOnWorldMap_BaseCamp",
  "bDisplayPvPItemNumOnWorldMap_Player",
  "AdditionalDropItemWhenPlayerKillingInPvPMode",
  "AdditionalDropItemNumWhenPlayerKillingInPvPMode",
  "bAdditionalDropItemWhenPlayerKillingInPvPMode",
  "bAllowEnhanceStat_Health",
  "bAllowEnhanceStat_Attack",
  "bAllowEnhanceStat_Stamina",
  "bAllowEnhanceStat_Weight",
  "bAllowEnhanceStat_WorkSpeed",
  "PlayerDataPalStorageUpdateCheckTickInterval",
  "AutoTransferMasterCheckIntervalSeconds",
  "AutoTransferMasterThresholdDays",
  "MaxGuildsPerFrame",
  "bEnableBuildingPlayerUIdDisplay",
  "BuildingNameDisplayCacheTTLSeconds",
];

export const EntryIdToEnumName: Record<string, string> = {
  DeathPenalty: "EPalOptionWorldDeathPenalty",
  Difficulty: "EPalOptionWorldDifficulty",
  LogFormatType: "EPalOptionWorldLogFormatType",
  RandomizerType: "EPalRandomizerType",
  CrossplayPlatforms: "EPalAllowConnectPlatform",
  DenyTechnologyList: "EPalDenyTechnology", // 假设的枚举类型名称
}
